version: 0.2

phases:

  install:
    commands:
      - apt-get update -y
      - apt-get install -y npm
      - apt-get install -y zip
      - npm i -g serverless
  build:
    commands:
      - ./build.sh
      - sls deploy --v