version: 0.2

phases:

  install:
    commands:
      - apt-get update -y
      - apt-get install -y nodejs npm
      - apt-get install -y zip
      - npm config set registry="http://registry.npmjs.org/"
      - npm i -g serverless
  build:
    commands:
      - ./build.sh
      - sls deploy --v