version: 2
jobs:
  build:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - run:
          name: restore
          command: dotnet restore
      - run:
          name: Run build scripts
          command: | 
            cd api/
            ./build.sh
      - store_artifacts:
          path: artifacts
  test:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - run:
          name: restore
          command: dotnet restore
      - run:
          name: Test api.Tests.csproj
          command: dotnet test ./api.Tests/api.Tests.csproj --logger "trx;LogFileName=../../artifacts/test-results/Api.Tests/result.trx"
      - run:
          name: Test Core.Tests
          command: dotnet test ./Core.Tests/Core.Tests.csproj --logger "trx;LogFileName=../../artifacts/test-results/Core.Tests/result.trx"
      - store_test_results:
          path: artifacts/test-results
  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test