version: 2
jobs:
  build:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - run:
          name: Check
          command: serverless --version
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date