version: 2
jobs:
  build_dev:
    working_directory: ~/repo
    docker:
      - image: dantaylor/serverless-build-helper:xunit-to-junit
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: restore
          command: |
            dotnet restore
      - run:
          name: Run build scripts
          command: | 
            cd api/
            ./build.sh
            dotnet build
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - artifacts
            - .
  api-unit-tests:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test api.Tests.csproj
          command: |
            dotnet restore
            cd api.Tests/
            dotnet xunit -fxversion 2.1.1 -namespace api.Tests -xml result.xml
            dotnet xunit-to-junit "result.xml" "../../artifacts/test-results/Api.Tests/junit/result.xml"
      - store_test_results:
          path: /root/project/artifacts/test-results/Api.Tests/junit
      - store_artifacts:
          path: /root/project/artifacts/test-results
  core-unit-tests:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test Core.Tests
          command: |
            dotnet restore
            cd Core.Tests/
            dotnet xunit -fxversion 2.1.1 -namespace Core.Tests -xml result.xml
            dotnet xunit-to-junit "result.xml" "../../artifacts/test-results/Core.Tests/junit/result.xml"
      - store_test_results:
          path: /root/project/artifacts/test-results/Core.Tests/junit
      - store_artifacts:
          path: /root/project/artifacts/test-results
  logging-tests:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test Logging.Tests
          command: |
            dotnet restore
            cd Logging.Tests/
            dotnet xunit -fxversion 2.1.1 -namespace Logging.Tests -xml result.xml
            dotnet xunit-to-junit "result.xml" "../../artifacts/test-results/Logging.Tests/junit/result.xml"
  deploy:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: deploy serverless code
          command: |
            STAGE=`echo ${CIRCLE_BRANCH} | sed 's/\//-/g'`
            sls config credentials --provider aws --key $aws_access_key_id --secret $aws_secret_access_key
            cd api/
            sls deploy --v --stage $STAGE
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - develop
                - /feature.*/
                - /release.*/
            tags:
              ignore: 
                - /destroy/
                - /finish.*/
      - api-unit-tests:
          requires:
            - build_dev
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - core-unit-tests:
          requires:
            - build_dev
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - logging-tests:
          requires:
            - build_dev
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - deploy:
          requires:
            - build_dev
            - api-unit-tests
            - core-unit-tests
            - logging-tests
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
#      - destroy:
#          filters:
#            tags:
#              only:
#                - /destroy/
#                - /finish.*/
