version: 2
jobs:
  build:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - run:
          name: restore
          command: dotnet restore
      - run:
          name: Test api.Tests.csproj
          command: dotnet test ./api.Tests/api.Tests.csproj --logger "trx;LogFileName=../../TestResults/Api.Tests/result.trx"
      - store_test_results:
          path: TestResults