version: 2
jobs:
  build_dev:
    working_directory: ~/repo
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: restore
          command: |
            dotnet restore
      - run:
          name: Run build scripts
          command: | 
            cd api/
            ./build.sh
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - artifacts
  api-unit-tests:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test api.Tests.csproj
          command: dotnet test ./api.Tests/api.Tests.csproj --logger "trx;LogFileName=../../artifacts/test-results/Api.Tests/result.xml"
      - run:
          name: Test IocFactory.Tests
          command: dotnet test ./IocFactory.Tests/IocFactory.Tests.csproj --logger "trx;LogFileName=../../artifacts/test-results/IocFactory.Tests/result.xml"
      - store_test_results:
          path: /root/project/artifacts/test-results
      - store_artifacts:
          path: artifacts/test-results
  core-unit-tests:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test Core.Tests
          command: dotnet test ./Core.Tests/Core.Tests.csproj --logger "trx;LogFileName=../../artifacts/test-results/Core.Tests/result.xml"
      - store_test_results:
          path: /root/project/artifacts/test-results
      - store_artifacts:
          path: artifacts/test-results
  ioc-factory-tests:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test IocFactory.Tests
          command: dotnet test ./IocFactory.Tests/IocFactory.Tests.csproj --logger "trx;LogFileName=../../artifacts/test-results/IocFactory.Tests/result.xml"
      - store_test_results:
          path: /root/project/artifacts/test-results
      - store_artifacts:
          path: artifacts/test-results
  deploy:
    docker:
      - image: dantaylor/serverless-build-helper
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: deploy serverless code
          command: |
            STAGE=`echo ${CIRCLE_BRANCH} | sed 's/\//-/g'`
            sls config credentials --provider aws --key $aws_access_key_id --secret $aws_secret_access_key
            cd api/
            sls deploy --v --stage $STAGE
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - develop
                - /feature.*/
                - /release.*/
            tags:
              ignore: 
                - /destroy/
                - /finish.*/
      - api-unit-tests:
          requires:
            - build_dev
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - core-unit-tests:
          requires:
            - build_dev
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - ioc-factory-tests:
          requires:
            - build_dev
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
      - deploy:
          requires:
            - build_dev
            - api-unit-tests
            - core-unit-tests
            - ioc-factory-tests
          filters:
            tags:
              ignore:
                - /destroy/
                - /finish.*/
#      - destroy:
#          filters:
#            tags:
#              only:
#                - /destroy/
#                - /finish.*/
