service: api

provider:
  name: aws
  stage: ${opt:stage, 'develop'}
  environment:
    ENVIRONMENT_PATH: ${self:provider.stage}
  runtime: dotnetcore2.0
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "ssm:GetParametersByPath"
        - "sqs:GetQueueAttributes"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        - "sqs:ListQueues"
        - "sqs:ChangeMessageVisibility"
        - "sqs:SendMessage"
      Resource: '*'
package:
  artifact: ../artifacts/deploy-package.zip 
  #TODO: need to put in the git-sha onto this and/or tag it.  Should I also be pushing this to S3?

functions:
  log:
    handler: CsharpHandlers::Api.Handler::Log
    environment: ${opt:stage, 'develop'}
    events:
      - http:
          path: log
          method: post
  persist:
    handler: CsharpHandlers::Api.Handler::Persist
    environment: ${opt:stage, 'develop'}
    events:
      - sqs:
          queueName: activity-log-queue-${opt:stage, 'develop'}
          arn:
            Fn::GetAtt:
              - IncomingLogQueue
              - Arn
resources:
  Resources:
    incomingQueueParameter:
      Type: AWS::SSM::Parameter
      DependsOn: IncomingLogQueue
      Properties:
        Name: /dancountability/${opt:stage, 'develop'}/settings/incoming-q-url
        Description: the queue url for the app to poll
        Type: String
        Value: 
          Ref: IncomingLogQueue
    loggingDb:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
          - AttributeName: InsertDate
            AttributeType: S
          - AttributeName: Text
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
          - AttributeName: InsertDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ActivityLog-${opt:stage, 'develop'}
        GlobalSecondaryIndexes:
          - IndexName: dateIndex
            KeySchema:
              - AttributeName: Text
                KeyType: HASH
              - AttributeName: InsertDate
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - Id
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    IncomingLogQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: activity-log-queue-${opt:stage, 'develop'}
        #different queues for different environments
          